### ISSUE TITLE
Default should be no since most answers are not the correct answer

### ISSUE THREAD

**Issue by ritvvijparrikh** [icfjknightfellows/ProtoGraph.Card.toQuiz#3]
<img width="221" alt="screen shot 2017-07-24 at 9 24 27 pm" src="https://user-images.githubusercontent.com/5548341/28532118-85c52dae-70b6-11e7-89c2-75beb8104b52.png">

**Comment by AashutoshSBhatt** [comment]
The quiz application requires at least one option correct when the mode is scoring. There is UI code dependent on this option value. This condition also occurs when the user is editing the form. This causes [https://github.com/icfjknightfellows/ProtoGraph.Card.toQuiz/issues/2](url)
