### ISSUE TITLE
Images disappeared?

### ISSUE THREAD

**Issue by ritvvijparrikh** [icfjknightfellows/ProtoGraph.Card.toQuiz#5]
<img width="1680" alt="screen shot 2017-07-24 at 9 35 31 pm" src="https://user-images.githubusercontent.com/5548341/28532657-14739ee0-70b8-11e7-8640-e85dc5d532de.png">

**Comment by AashutoshSBhatt** [comment]
Resolved By: [https://github.com/pykih/ProtoGraph.Container.toCardForm/commit/8edd4c2bb6bb6819c93db48522964c8d4ff00ee0](url)
